/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package Parser.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 13;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 14;
  /** RegularExpression Id. */
  int DEFINE = 15;
  /** RegularExpression Id. */
  int DOMAIN = 16;
  /** RegularExpression Id. */
  int REQUIREMENTS = 17;
  /** RegularExpression Id. */
  int TYPES = 18;
  /** RegularExpression Id. */
  int EITHER = 19;
  /** RegularExpression Id. */
  int CONSTANTS = 20;
  /** RegularExpression Id. */
  int PREDICATES = 21;
  /** RegularExpression Id. */
  int FUNCTIONS = 22;
  /** RegularExpression Id. */
  int ACTION = 23;
  /** RegularExpression Id. */
  int PARAMETERS = 24;
  /** RegularExpression Id. */
  int PRECONDITION = 25;
  /** RegularExpression Id. */
  int EFFECT = 26;
  /** RegularExpression Id. */
  int PREFERENCE = 27;
  /** RegularExpression Id. */
  int WHEN = 28;
  /** RegularExpression Id. */
  int DURATIVE_ACTION = 29;
  /** RegularExpression Id. */
  int DURATION = 30;
  /** RegularExpression Id. */
  int CONDITION = 31;
  /** RegularExpression Id. */
  int DERIVED = 32;
  /** RegularExpression Id. */
  int PROBLEM = 33;
  /** RegularExpression Id. */
  int P_DOMAIN = 34;
  /** RegularExpression Id. */
  int OBJECTS = 35;
  /** RegularExpression Id. */
  int INIT = 36;
  /** RegularExpression Id. */
  int GOAL = 37;
  /** RegularExpression Id. */
  int METRIC = 38;
  /** RegularExpression Id. */
  int STRIPS = 39;
  /** RegularExpression Id. */
  int TYPING = 40;
  /** RegularExpression Id. */
  int NON_DETERMINISTIC = 41;
  /** RegularExpression Id. */
  int NEGATIVE_PRECONDITIONS = 42;
  /** RegularExpression Id. */
  int DISJUNCTIVE_PRECONDITIONS = 43;
  /** RegularExpression Id. */
  int EQUALITY = 44;
  /** RegularExpression Id. */
  int EXISTENTIAL_PRECONDITIONS = 45;
  /** RegularExpression Id. */
  int UNIVERSAL_PRECONDITIONS = 46;
  /** RegularExpression Id. */
  int QUANTIFIED_PRECONDITIONS = 47;
  /** RegularExpression Id. */
  int CONDITIONAL_EFFECTS = 48;
  /** RegularExpression Id. */
  int ACTION_COSTS = 49;
  /** RegularExpression Id. */
  int FLUENTS = 50;
  /** RegularExpression Id. */
  int NUMERIC_FLUENTS = 51;
  /** RegularExpression Id. */
  int OBJECT_FLUENTS = 52;
  /** RegularExpression Id. */
  int GOAL_UTILITIES = 53;
  /** RegularExpression Id. */
  int ADL = 54;
  /** RegularExpression Id. */
  int DURATIVE_ACTIONS = 55;
  /** RegularExpression Id. */
  int DERIVED_PREDICATES = 56;
  /** RegularExpression Id. */
  int TIMED_INITIAL_LITERALS = 57;
  /** RegularExpression Id. */
  int PREFERENCES = 58;
  /** RegularExpression Id. */
  int CONSTRAINTS = 59;
  /** RegularExpression Id. */
  int CONTINUS_EFFECTS = 60;
  /** RegularExpression Id. */
  int DURATION_INEQUALITIES = 61;
  /** RegularExpression Id. */
  int GREATER = 62;
  /** RegularExpression Id. */
  int LESS = 63;
  /** RegularExpression Id. */
  int GEQUAL = 64;
  /** RegularExpression Id. */
  int LEQUAL = 65;
  /** RegularExpression Id. */
  int EQUAL = 66;
  /** RegularExpression Id. */
  int MUL = 67;
  /** RegularExpression Id. */
  int DIV = 68;
  /** RegularExpression Id. */
  int ADD = 69;
  /** RegularExpression Id. */
  int SUB = 70;
  /** RegularExpression Id. */
  int ASSIGN = 71;
  /** RegularExpression Id. */
  int SCALE_UP = 72;
  /** RegularExpression Id. */
  int SCALE_DOWN = 73;
  /** RegularExpression Id. */
  int INCREASE = 74;
  /** RegularExpression Id. */
  int DECREASE = 75;
  /** RegularExpression Id. */
  int OR = 76;
  /** RegularExpression Id. */
  int AND = 77;
  /** RegularExpression Id. */
  int ONEOF = 78;
  /** RegularExpression Id. */
  int IMPLY = 79;
  /** RegularExpression Id. */
  int NOT = 80;
  /** RegularExpression Id. */
  int FORALL = 81;
  /** RegularExpression Id. */
  int EXISTS = 82;
  /** RegularExpression Id. */
  int ALWAYS = 83;
  /** RegularExpression Id. */
  int SOMETIME = 84;
  /** RegularExpression Id. */
  int WITHIN = 85;
  /** RegularExpression Id. */
  int AT_MOST_ONCE = 86;
  /** RegularExpression Id. */
  int SOMETIME_AFTER = 87;
  /** RegularExpression Id. */
  int SOMETIME_BEFORE = 88;
  /** RegularExpression Id. */
  int ALWAYS_WITHIN = 89;
  /** RegularExpression Id. */
  int HOLD_DURING = 90;
  /** RegularExpression Id. */
  int HOLD_AFTER = 91;
  /** RegularExpression Id. */
  int AT = 92;
  /** RegularExpression Id. */
  int START = 93;
  /** RegularExpression Id. */
  int END = 94;
  /** RegularExpression Id. */
  int OVER = 95;
  /** RegularExpression Id. */
  int ALL = 96;
  /** RegularExpression Id. */
  int TOTAL_TIME = 97;
  /** RegularExpression Id. */
  int TOTAL_COST = 98;
  /** RegularExpression Id. */
  int MAXIMIZE = 99;
  /** RegularExpression Id. */
  int MINIMIZE = 100;
  /** RegularExpression Id. */
  int IS_VIOLATED = 101;
  /** RegularExpression Id. */
  int VAR_DURATION = 102;
  /** RegularExpression Id. */
  int CONTINUOUS_VARIABLE = 103;
  /** RegularExpression Id. */
  int NUMBER_TYPE = 104;
  /** RegularExpression Id. */
  int OBJECT_TYPE = 105;
  /** RegularExpression Id. */
  int VARIABLE_SYMBOL = 106;
  /** RegularExpression Id. */
  int SYMBOL = 107;
  /** RegularExpression Id. */
  int NUMBER = 108;
  /** RegularExpression Id. */
  int DIGIT = 109;
  /** RegularExpression Id. */
  int LETTER = 110;
  /** RegularExpression Id. */
  int SEPARATOR = 111;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\";\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"(\"",
    "\")\"",
    "\"define\"",
    "\"domain\"",
    "\":requirements\"",
    "\":types\"",
    "\"either\"",
    "\":constants\"",
    "\":predicates\"",
    "\":functions\"",
    "\":action\"",
    "\":parameters\"",
    "\":precondition\"",
    "\":effect\"",
    "\"preference\"",
    "\"when\"",
    "\":durative-action\"",
    "\":duration\"",
    "\":condition\"",
    "\":derived\"",
    "\"problem\"",
    "\":domain\"",
    "\":objects\"",
    "\":init\"",
    "\":goal\"",
    "\":metric\"",
    "\":strips\"",
    "\":typing\"",
    "\":non-deterministic\"",
    "\":negative-preconditions\"",
    "\":disjunctive-preconditions\"",
    "\":equality\"",
    "\":existential-preconditions\"",
    "\":universal-preconditions\"",
    "\":quantified-preconditions\"",
    "\":conditional-effects\"",
    "\":action-costs\"",
    "\":fluents\"",
    "\":numeric-fluents\"",
    "\":object-fluents\"",
    "\":goal-utilities\"",
    "\":adl\"",
    "\":durative-actions\"",
    "\":derived-predicates\"",
    "\":timed-initial-literals\"",
    "\":preferences\"",
    "\":constraints\"",
    "\":continus-effects\"",
    "\":duration-inequalities\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"assign\"",
    "\"scale-up\"",
    "\"scale-down\"",
    "\"increase\"",
    "\"decrease\"",
    "\"or\"",
    "\"and\"",
    "\"oneof\"",
    "\"imply\"",
    "\"not\"",
    "\"forall\"",
    "\"exists\"",
    "\"always\"",
    "\"sometime\"",
    "\"within\"",
    "\"at-most-once\"",
    "\"sometime-after\"",
    "\"sometime-before\"",
    "\"always-within\"",
    "\"hold-during\"",
    "\"hold-after\"",
    "\"at\"",
    "\"start\"",
    "\"end\"",
    "\"over\"",
    "\"all\"",
    "\"total-time\"",
    "\"total-cost\"",
    "\"maximize\"",
    "\"minimize\"",
    "\"is-violated\"",
    "\"?duration\"",
    "\"#t\"",
    "\"number\"",
    "\"object\"",
    "<VARIABLE_SYMBOL>",
    "<SYMBOL>",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "<SEPARATOR>",
  };

}
